/*
 * generated by Xtext
 */
package org.applause.lang.ui;

import org.applause.lang.ui.builder.ApplauseBuilderParticipant;
import org.applause.lang.ui.builder.EclipseOutputConfigurationProviderExt;
import org.applause.lang.ui.builder.FixedEclipseResourceFileSystemAccess2;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.builder.EclipseOutputConfigurationProvider;
import org.eclipse.xtext.builder.EclipseResourceFileSystemAccess2;
import org.eclipse.xtext.builder.IXtextBuilderParticipant;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ApplauseDslUiModule extends org.applause.lang.ui.AbstractApplauseDslUiModule {
	public ApplauseDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	// TODO is this needed? still from Karsten's blog
	public org.eclipse.core.resources.IWorkspaceRoot bindIWorkspaceRootToInstance() {
		return org.eclipse.core.resources.ResourcesPlugin.getWorkspace().getRoot();
	}
	
	@Override
	public Class<? extends IXtextBuilderParticipant> bindIXtextBuilderParticipant() {
		return ApplauseBuilderParticipant.class;
	}
	
	public Class<? extends EclipseOutputConfigurationProvider> bindEclipseOutputConfigurationProvider() {
		return EclipseOutputConfigurationProviderExt.class;
	}
	
	public Class<?extends EclipseResourceFileSystemAccess2> bindEclipseResourceFileSystemAccess2() {
		return FixedEclipseResourceFileSystemAccess2.class;
	}
}
