<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="applauseDsl"
    nsURI="http://www.applause.org/lang/ApplauseDsl" nsPrefix="applauseDsl">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" eType="#//Application"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ModelElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Application">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="splash" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buttons" upperBound="-1"
        eType="#//TabbarButton" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDescription">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="many" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#//TypeDescription"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectReference" eSuperTypes="#//Expression #//ScalarExpression #//CollectionExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="#//VariableDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tail" eType="#//ObjectReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScalarExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//Expression #//ScalarExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringFunction" eSuperTypes="#//Expression #//ScalarExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionLiteral" eSuperTypes="#//Expression #//CollectionExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//ScalarExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionFunction" eSuperTypes="#//Expression #//CollectionExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="TabbarButton">
    <eStructuralFeatures xsi:type="ecore:EReference" name="title" eType="#//ScalarExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="icon" eType="#//ScalarExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="view" eType="#//ViewCall"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="platformType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#//TypeDescription"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentProvider" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//Parameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolver" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="many" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="url" eType="#//ScalarExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selection" eType="#//ScalarExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProviderConstruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="View" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//Parameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SectionedView" eSuperTypes="#//View">
    <eStructuralFeatures xsi:type="ecore:EReference" name="title" eType="#//ScalarExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sections" upperBound="-1"
        eType="#//ViewSection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableView" eSuperTypes="#//SectionedView"/>
  <eClassifiers xsi:type="ecore:EClass" name="DetailsView" eSuperTypes="#//SectionedView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="header" eType="#//ViewHeader"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomView" eSuperTypes="#//View">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objclass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewHeader">
    <eStructuralFeatures xsi:type="ecore:EReference" name="title" eType="#//ScalarExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subtitle" eType="#//ScalarExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="details" eType="#//ScalarExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="image" eType="#//ScalarExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="title" eType="#//ScalarExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" upperBound="-1"
        eType="#//SectionCell" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SectionCell">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//CellType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iterator" eType="#//CollectionIterator"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//ScalarExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="details" eType="#//ScalarExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="image" eType="#//ScalarExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="query" eType="#//ScalarExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//ViewAction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CellType">
    <eLiterals name="default" literal="Default"/>
    <eLiterals name="defaultWithDisclosure" value="1" literal="DefaultWithDisclosure"/>
    <eLiterals name="value2" value="2" literal="Value2"/>
    <eLiterals name="double" value="3" literal="Double"/>
    <eLiterals name="subtitle" value="4" literal="Subtitle"/>
    <eLiterals name="maps" value="5" literal="Map"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionIterator" eSuperTypes="#//VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="collection" eType="#//CollectionExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalOpen" eSuperTypes="#//ViewAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="url" eType="#//ScalarExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewCall" eSuperTypes="#//ViewAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="view" eType="#//View"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provider" eType="#//ProviderConstruction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringConcat" eSuperTypes="#//StringFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//ScalarExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringReplace" eSuperTypes="#//StringFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ScalarExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="match" eType="#//ScalarExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="replacement" eType="#//ScalarExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringUrlConform" eSuperTypes="#//StringFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ScalarExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringSplit" eSuperTypes="#//CollectionFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ScalarExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delimiter" eType="#//ScalarExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="#//VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ScalarExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexProviderConstruction" eSuperTypes="#//ProviderConstruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="provider" eType="#//ContentProvider"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argument" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleProviderConstruction" eSuperTypes="#//ProviderConstruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
