/*
 * generated by Xtext
 */
package org.applause.lang.ui.contentassist

import org.applause.lang.ui.contentassist.AbstractApplauseDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ApplauseDslProposalProvider extends AbstractApplauseDslProposalProvider {
}
