/*
 * generated by Xtext
 */
package org.applause.lang;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ApplauseDslRuntimeModule extends org.applause.lang.AbstractApplauseDslRuntimeModule {

}
