/*
 * generated by Xtext
 */
package org.applause.lang.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.applause.lang.ui.internal.ApplauseDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ApplauseDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ApplauseDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ApplauseDslActivator.getInstance().getInjector(ApplauseDslActivator.ORG_APPLAUSE_LANG_APPLAUSEDSL);
	}
	
}
