/*
* generated by Xtext
*/
package org.applause.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class ApplauseDslTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
