/*
* generated by Xtext
*/
package org.applause.util.xcode.projectfile;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PbxprojUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.applause.util.xcode.projectfile.ui.internal.PbxprojActivator.getInstance().getInjector("org.applause.util.xcode.projectfile.Pbxproj");
	}
	
}
