/*
 * generated by Xtext
 */
package de.itemis.mobilizer.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.IGenerator
import org.eclipse.xtext.generator.IFileSystemAccess

class AppModelDslGenerator implements IGenerator {
	
	@Inject
	de.itemis.mobilizer.generator.iphone.Generator as iPhone
	
	override void doGenerate(Resource resource, IFileSystemAccess fsa) {
		//iPhone.generate();
	}
}
